### ISSUE TITLE
[Bug] Error while running demo

### ISSUE THREAD

**Issue by mbm-rafal** [faceyspacey/redux-first-router-demo#18]
```
➜  redux-first-router-demo git:(master) yarn
yarn install v0.23.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "stats-webpack-plugin@0.5.0" has incorrect peer dependency "webpack@^1.0||^2.1.0-beta||^2.2.0-rc".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 44.84s.
➜  redux-first-router-demo git:(master) ✗ yarn start
yarn start v0.23.3
$ npm run clean && cross-env NODE_ENV=development babel-watch server/index.js

> redux-first-router-demo@1.0.0 clean /Users/rafal/Documents/Work/projects/test3/redux-first-router-demo
> rimraf buildClient buildServer

/Users/rafal/Documents/Work/projects/test3/redux-first-router-demo/node_modules/babel-plugin-universal-import/index.js:3
module.exports = function ({ types: t, template }) {
                           ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /Users/rafal/Documents/Work/projects/test3/redux-first-router-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:178:20
    at Array.map (native)
    at Function.normalisePlugins (/Users/rafal/Documents/Work/projects/test3/redux-first-router-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
error Command failed with exit code 1.
```

**Comment by faceyspacey** [comment]
It seems you're running an older version of node that doesn't support destructuring. The babel plugin runs in node at compile time and `({ types: t, remplate })` is destructuring. 

I'm inclined to change it so that nobody runs into this issue, but this is the first time I'm hearing about it and I've seen many babel plugins that do it.

**Comment by mbm-rafal** [comment]
Right. My https://github.com/creationix/nvm provide me with 5.x version and there was an issue. Building on 6.x works! Thanks!
