### ISSUE TITLE
Error when sharing code between client and server in production build

### ISSUE THREAD

**Issue by peterpanse** [faceyspacey/redux-first-router-demo#47]
Picture there are some constants you want to share between client and server but not duplicate that code.

My approach was to create a file named constants in file path: `./src/constants.js` and export an object from that file. Now I want to import that file in lets say `./server/index.js` and use those constants in server context.

While running the development build everything works fine.

As soon as I try to run the production build and try to execute it, I get the following error:

```
> redux-first-router-demo@1.0.0 build:node /Users/peterpanse/Projects/redux-first-router-demo
> cross-env NODE_ENV=production babel server -d buildServer --ignore configureStore,render

server/api.js -> buildServer/api.js
server/index.js -> buildServer/index.js
server/test.js -> buildServer/test.js

> redux-first-router-demo@1.0.0 serve /Users/peterpanse/Projects/redux-first-router-demo
> cross-env NODE_ENV=production node buildServer/index.js

/Users/peterpanse/Projects/redux-first-router-demo/src/data/test.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/peterpanse/Projects/redux-first-router-demo/buildServer/index.js:39:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-first-router-demo@1.0.0 serve: `cross-env NODE_ENV=production node buildServer/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-first-router-demo@1.0.0 serve script.
```

That is the part I'd like to highlight:

```
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

Whats wrong?

It is easy to reproduce: Just download the demo repo, create a file in `./src` and import it in `./server`. Guaranteed error when trying to execute the production build.

**Comment by faceyspacey** [comment]
that file actually isn't being built to run in the "bootstrap" server code. See:

https://github.com/faceyspacey/redux-first-router-demo/blob/master/package.json#L15

Only 2 files in `/server` are being built to run in the "bootstrap" code. The other 2 files just happen to be in that folder because they are key to how the server works, but they in fact are bundled into the webpack bundled code that runs on the server. 

The quickfix is to put those constants in `/server`, but that's a weird place to import from in client code. Another option is to create a `/shared` folder and make sure the `build:node` script builds that as well.
